#!/bin/bash
for i 
do
  echo "Flashing bootloader on node "$i
  FTDI_SERIAL=$(./get_ftdi_serial $i)
  echo "Trying to flash via ftdi with serial: "$FTDI_SERIAL
  cd ../repos/software-cm-2013-inga-bootloader/
  make bang SERIAL=$FTDI_SERIAL AVRDUDE_FLAGS="-e"
  cd -
done
