#!/bin/bash

source utils.sh

if [ "$#" -lt "1" ]; then
    print_info "Missing parameters"
    print_info "Usage: $0 {path of serial device}+" 
    exit
fi

for i 
do
  print_info "Flashing bootloader on node $i"
  source ./get_ftdi_serial $i 

  if [ ! -n "${FTDI_SERIAL}" ]; then
    print_info "Error: SERIAL $FTDI_SERIAL is unknown."
    exit
  fi

  print_info "Trying to flash via ftdi bitbang with serial: $FTDI_SERIAL"
  cd ../repos/inga_bootloader/
  make bang SERIAL=$FTDI_SERIAL AVRDUDE_FLAGS="-e"
  cd - > /dev/null
done
