#!/bin/bash
source utils.sh

REPO_CONTIKI="../repos/contiki-inga"
INGA_TOOL_PATH=$REPO_CONTIKI"/tools/inga/inga_tool"

if [ "$#" -lt "1" ]; then
    print_info "Missing parameters"
    print_info "Usage: $0 {path of serial device}+" 
    exit
fi

if [ ! -x $INGA_TOOL_PATH"/inga_tool" ]; then
  print_info "inga_tool not found in $INGA_TOOL_PATH trying to compile it..."
  cd $INGA_TOOL_PATH > /dev/null
  make > /dev/null
  cd - > /dev/null
fi
  
DEVICE=$1
FTDI_SERIAL="$($INGA_TOOL_PATH/inga_tool -s -d $DEVICE | grep "Serial:" | cut -f 8 -d" ")"
echo $FTDI_SERIAL
export FTDI_SERIAL
